### ISSUE TITLE
Module not found: Can't resolve 'react-native-web/dist/exports/ColorPropType'

### ISSUE THREAD

**Issue by yangup** [react-native-elements/react-native-elements-app#110]
D:/study/react-native-elements-app/node_modules/expo-linear-gradient/build/LinearGradient.js
Module not found: Can't resolve 'react-native-web/dist/exports/ColorPropType' in 'D:\study\react-native-elements-app\node_modules\expo-linear-gradient\build'

![image](https://user-images.githubusercontent.com/28469164/87149172-54d71280-c2e2-11ea-9f13-2719d87696ce.png)

**Comment by leonaburime** [comment]
> D:/study/react-native-elements-app/node_modules/expo-linear-gradient/build/LinearGradient.js
> Module not found: Can't resolve 'react-native-web/dist/exports/ColorPropType' in 'D:\study\react-native-elements-app\node_modules\expo-linear-gradient\build'
> 
> ![image](https://user-images.githubusercontent.com/28469164/87149172-54d71280-c2e2-11ea-9f13-2719d87696ce.png)

Did you ever figure this out?

Also want to reference https://github.com/necolas/react-native-web/issues/1537

**Comment by khushal87** [comment]
Are you running the application on web? See if https://github.com/react-native-elements/react-native-elements-app/pull/141 helps  you, it should work well. Thanks, feel free to inform if any other issue comes or if its related to other stuff. @yangup

**Comment by khushal87** [comment]
The issue can be closed now after the latest changes in the code done recently. Thank you. @flyingcircle @pranshuchittora @yangup
