### ISSUE TITLE
Expo app preview needs updating v34 => v35

### ISSUE THREAD

**Issue by cube-dan** [react-native-elements/react-native-elements-app#112]
Greets Team RNE, 

Just a quick heads up here. Your Expo preview app located here is non functional: https://expo.io/@monte9/react-native-elements-app

Instead of the app this error message is shown: 
![IMG_3609](https://user-images.githubusercontent.com/8559668/87701332-abae7300-c74c-11ea-80bd-921a83a41a95.jpeg)

**Comment by flyingcircle** [comment]
Updated to expo v38 and updated the link in the docs.
