### ISSUE TITLE
Issue loading in Expo Client: SDK v35.0.0 minimum is required

### ISSUE THREAD

**Issue by mryechkin** [react-native-elements/react-native-elements-app#115]
When I try loading the demo app in [Expo](https://expo.io/@monte9/react-native-elements-app), I get an error screen in Expo Client, with the following message:

```
The experience you requested uses Expo SDK v34.0.0, but this copy of Expo Client requires at least v35.0.0. The author should update their experience to a newer Expo SDK version.
```

Platform: **iOS**
Expo Client Version: **2.16.0.108985**

**Comment by flyingcircle** [comment]
`next` branch is on expo 39
