### ISSUE TITLE
Which branch/version is deployed?

### ISSUE THREAD

**Issue by shauntarves** [react-native-elements/react-native-elements-app#117]
Hi,

Sorry for asking this basic question, but I'm trying to follow the source code and map it to the deployed web app at https://react-native-elements.github.io/react-native-elements-app/. I'm struggling to understand the navigation, specifically where the stack navigator that I see when I click on "Buttons" in the drawer navigator is defined.

**Comment by flyingcircle** [comment]
I don't think this app would likely work for web, I use this repo for web related testing: https://github.com/react-native-elements/create-react-app-example
