### ISSUE TITLE
tab section call Navigator , is it a problem?

### ISSUE THREAD

**Issue by itagakixt** [react-native-elements/react-native-elements-app#12]
hello,

Using react-native-hackathon-starter, I incorporated one application into this environment.
my application is calling Navigator in render section.
I wonder this kind of using Navigator will make a problem or not.
I did not study deeply both environment.

Currently my application seems to works without error.

I 'm afraid futures problem.

Any suggestion appreciated.

Thanks
Shoji

**Comment by Monte9** [comment]
Hi @itagakixt! As long as your class is named `Navigator` and you use this same name in the render method it should be fine. 
One of the easiest ways to figure out if it's a problem is your application won't run. In your case it seems to be working fine, so I wouldn't worry about it.

**Comment by dabit3** [comment]
@Monte9 thanks!
