### ISSUE TITLE
Adding prettier as a dev dependency

### ISSUE THREAD

**Issue by abhishekkumar08** [react-native-elements/react-native-elements-app#127]
## Description
We can better add prettier to the repo: https://www.npmjs.com/package/prettier
So whenever we will run ```npm run prettify```, It will automatically format the whole code.
I can make a PR for that, if approved. The code does contain a script for prettier but it doesn't have the required dependency,
so if the user doesn't have ```prettier``` installed globally the command won't run.

**PS: The repo doesn't have a issue template. Can I create on the same?**

**Comment by flyingcircle** [comment]
I think what is more common is `eslint` for this kind of task which is already there with `yarn lint`
