### ISSUE TITLE
Migrating class based components to functional components

### ISSUE THREAD

**Issue by khushal87** [react-native-elements/react-native-elements-app#136]
Currently some of the components in the views are **Class based** as per the latest Pull, Moving to **Functional component based approach** will be a great stuff and I believe that will be relevant for the application.

Example:

- pricing.js
- ratings.js
- settings.js(migrating will also solve the switch issue as it will be easy fix)
- profile.js
- inputs.js
- fonts;js
- button.js
- login/screen2.js,screen2.js,index.js
- lists

As you can notice that some of them are Functional components and some are Class based, so these can be made uniform.

**Comment by khushal87** [comment]
I want to work on the same if it is not assigned to any one can I? Awaiting your reply for the same. Thanks @pranshuchittora @Monte9

**Comment by flyingcircle** [comment]
If you run `yarn lint` I'm hitting a couple of these errors:
```
React Hook useEffect has a missing dependency: 'props'. Either include it or remove the dependency array
```

**Comment by khushal87** [comment]
I will fix it now.

**Comment by khushal87** [comment]
I am working on the linting warning and issues which are coming up. Thanks.

**Comment by khushal87** [comment]
@flyingcircle `'redButton' is assigned a value but never used` can this be ignored or fixed?

**Comment by flyingcircle** [comment]
either or. If it's unused, then it can be deleted.

**Comment by khushal87** [comment]
Fixed by https://github.com/react-native-elements/react-native-elements-app/pull/139
