### ISSUE TITLE
The web version of the app doesn't seem to work

### ISSUE THREAD

**Issue by khushal87** [react-native-elements/react-native-elements-app#140]
I tried running the application on web, but the app doesn't work and reports some errors. I want to fix them and see if I can make it work on web. This will give users a great flexibility. Can I pick up this issue? @flyingcircle

**Comment by flyingcircle** [comment]
Go for it: Doing something like suggested here might be necessary: https://github.com/react-native-elements/react-native-elements-app/issues/114

**Comment by khushal87** [comment]
Yes, after fixing that, now I am getting 
`C:/Users/hrith/react-native-elements-app/node_modules/react-native-touchable-scale/src/TouchableScale.js
Attempted import error: 'ViewPropTypes' is not exported from 'react-native-web/dist/index'.
URIError: Failed to decode param '/%PUBLIC_URL%service-worker.js'`
looking for a potential fix. Hope to get soon.

**Comment by khushal87** [comment]
Fixed and created a PR, awaiting feedback https://github.com/react-native-elements/react-native-elements-app/pull/141
