### ISSUE TITLE
No logo on expo-web view of the app

### ISSUE THREAD

**Issue by abhishekkumar08** [react-native-elements/react-native-elements-app#142]
## Description
Logo doesn't seem to appear on expo-webview of the app.

## Screenshots
![image](https://user-images.githubusercontent.com/59651136/111206248-28506480-85ee-11eb-93e8-f8cfb2262c99.png)

**Comment by khushal87** [comment]
@abhishekkumar08 Are you still working on it?

**Comment by abhishekkumar08** [comment]
@khushal87 I haven't find the solution to this issue, been busy for some days, if you could help me it would be very nice.

**Comment by khushal87** [comment]
@abhishekkumar08 Let me see it on my end. Thanks. I Will suggest a solution here

**Comment by khushal87** [comment]
Hey @abhishekkumar08 You can see at my fix. Thank you.

**Comment by khushal87** [comment]
@abhishekkumar08 @flyingcircle @pranshuchittora  Please close the issue if it is resolved
