### ISSUE TITLE
Incorrect widths of tooltip components

### ISSUE THREAD

**Issue by HariAcidReign** [react-native-elements/react-native-elements-app#157]
**Expected behavior:**
![image](https://user-images.githubusercontent.com/58134096/111410496-db0fe800-86fe-11eb-9247-cc33da90fa7e.png)
![image](https://user-images.githubusercontent.com/58134096/111410500-dd724200-86fe-11eb-8ced-bd71120aef3f.png)

**Actual behavior:**
![image](https://user-images.githubusercontent.com/58134096/111410509-e19e5f80-86fe-11eb-9f93-dca03b754f06.png)
![image](https://user-images.githubusercontent.com/58134096/111410513-e400b980-86fe-11eb-90af-dba6e497c126.png)

**Reason**: The width is unable to accommodate all the text inside each tooltip.

**Comment by khushal87** [comment]
Hey @HariAcidReign . Does that create much difference?

**Comment by HariAcidReign** [comment]
Sure does! It's a good UI experience to see things fully working and rendering their text as they should :)
