### ISSUE TITLE
LinearProgress is not rendered properly :  import error: 'LinearProgress' is not exported from 'react-native-elements'

### ISSUE THREAD

**Issue by Abhishek765** [react-native-elements/react-native-elements-app#168]
During testing the Components found one Bug in LinearProgress:

![image](https://user-images.githubusercontent.com/43133456/111755777-7c459c80-88bf-11eb-89b4-2ce375435247.png)

Due to this Issue, the Component (LinearProgress) is not rendered Properly and we got only Blank Page: 

![image](https://user-images.githubusercontent.com/43133456/111756712-8916c000-88c0-11eb-95e0-cb63b5dbe3c8.png)

**_We will get a blank after clicking on LinearProgress:_** 

![image](https://user-images.githubusercontent.com/43133456/111756881-b95e5e80-88c0-11eb-85df-bf9993ef46dd.png)

This needs to be fixed.

**Comment by Abhishek765** [comment]
@arpitBhalla can you comment on this I think you added this component, right?

**Comment by arpitBhalla** [comment]
@Abhishek765 let me check

**Comment by arpitBhalla** [comment]
@Abhishek765 I hope after pulling you reinstall the package?....

**Comment by flyingcircle** [comment]
This is not correct. You need to update the RNE code in the app `yarn add https://github.com/react-native-elements/react-native-elements`
