### ISSUE TITLE
I don't see the left sidebar.

### ISSUE THREAD

**Issue by anhchuyen** [react-native-elements/react-native-elements-app#19]
This new release has issue with left sidebar, I don't see it when running on IOS emulator..
![screen shot 2017-01-16 at 1 21 44 pm](https://cloud.githubusercontent.com/assets/5973048/21972835/fbbe4f7a-dbee-11e6-9172-51e812b76bad.png)

**Comment by Monte9** [comment]
@anhchuyen This should be fixed in the PR #16 

PR has been merged into master. Pull changes from master and this issue should be resolved.

**Comment by anhchuyen** [comment]
thank you!
