### ISSUE TITLE
undefined is not an object (evaluating 'FS.bundledAssets')

### ISSUE THREAD

**Issue by navid-kalaei** [react-native-elements/react-native-elements-app#58]
RNE demo app won't run due to this error:
![undefined](https://user-images.githubusercontent.com/7106251/44233785-126e2f00-a1ba-11e8-8496-ffb843e294e0.png)
The buggy code is located at `node_modules/expo/src/Asset.js`:
 ```
import { NativeModules, PixelRatio, Platform } from 'react-native';
import AssetRegistry from 'react-native/Libraries/Image/AssetRegistry';
import AssetSourceResolver from 'react-native/Libraries/Image/AssetSourceResolver';
import resolveAssetSource from 'react-native/Libraries/Image/resolveAssetSource';

import Constants from './Constants';

const FS = NativeModules.ExponentFileSystem;

// Fast lookup check if assets are available in the local bundle.
const bundledAssets = new Set(FS.bundledAssets || []);
```

The package.json is:
```json
{
  "name": "react-native-elements-app",
  "version": "1.0.0",
  "description": "Demo app for React Native Elements UI Library",
  "author": "Monte Thakkar",
  "private": true,
  "main": "main.js",
  "dependencies": {
    "@expo/vector-icons": "6.3.0",
    "expo": "26.0.0",
    "lodash": "^4.17.4",
    "react": "16.3.0-alpha.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-26.0.0.tar.gz",
    "react-native-touchable-scale": "2.0.0",
    "react-native-elements": "^1.0.0-beta3",
    "react-native-ratings": "^5.3.0",
    "react-navigation": "1.5.8"
  },
  "scripts": {
    "postinstall": "git submodule update",
    "clean-install":
      "rm -rf node_modules && npm cache clean --force && watchman watch-del-all && npm install"
  }
}
```

Thanks in advance for considering this issue.

UPDATE:
I created a new project using `create-react-native-app` and copied the files and faced a new problem:
![type](https://user-images.githubusercontent.com/7106251/44259433-b392cf00-a226-11e8-9e4a-aab8c0cd04e9.png)

**Comment by xavier-villelegier** [comment]
Could you try to clone again from `master` and run it through the [Expo CLI](https://docs.expo.io/versions/v31.0.0/introduction/installation.html#local-development-tool-expo-cli) ?

**Comment by Monte9** [comment]
We have made major improvements to this app such as updated Expo version, `react-navigation` v3, support for React Native Web` etc.

Also, I have updated the readme with [up-to-date instructions](https://github.com/Monte9/react-native-elements-app#run-it-locally) on how to run the app locally & also on `web`. Hope this helps.
