### ISSUE TITLE
Extremely slow on real iOS10 device

### ISSUE THREAD

**Issue by ssssssssssss** [react-native-elements/react-native-elements-app#6]
Dear all,

I've been running this project on real device, but faced an extremely slow response while clicking side menu and the 3rd tabbar. It looks like it's "rendering" a real large UI set.

Device: iPhone 6s
OS: iOS 10
Toolchain: XCode 8 (Didn't change compile flags)

**Comment by SupriyaKalghatgi** [comment]
+1

**Comment by ekhall** [comment]
I was having this same problem but upgraded to RN 0.34.1 and changed the scheme to Release. That seems to have helped.

**Comment by ssssssssssss** [comment]
@ekhall Upgraded to 0.34.1 and change the scheme to release mode doesn't help.

**Comment by dabit3** [comment]
Using the release scheme seems to be working super fast on my end. @ssssssssssss @SupriyaKalghatgi any way you an upload your build to a repo and let me take a look?

**Comment by jamesholcomb** [comment]
I upgraded to 0.34.1 but it's very slow when transitioning from About to Contact (7s) on iOS 9.3 sim.

**Comment by SupriyaKalghatgi** [comment]
@dabit3 Usually apps lag in debug mode
But this app runs extremely slow in debug mode compared to other apps

**Comment by jamesholcomb** [comment]
Changing the `ref` string attributes to callback attributes on the `<InputForm>` elements in Contact.js fixed the transition lag.

**Comment by dabit3** [comment]
@jamesholcomb Thanks for figuring this out. I was having a hard time finding the issue. I'll see if I can't figure out why using the ref attributes is causing the slowdown..

**Comment by dabit3** [comment]
This has been fixed in the latest release.

**Comment by anandmani** [comment]
Sorry, I'm new to Mobile development. What do you mean by 'release scheme'?
