### ISSUE TITLE
npm install doesn't work

### ISSUE THREAD

**Issue by jfaraklit** [react-native-elements/react-native-elements-app#60]
Running npm install takes about 15 minutes and finally fails with only .stage under node_modues. 

`error code EINTEGRITY
12596 error sha512....`

Any thoughts? 

![image](https://user-images.githubusercontent.com/14077606/45145345-68693d80-b18e-11e8-9a93-1bb901fb649d.png)

Tried couple of versions. Now trying with :
node 6.11.3 -  npm 4.6.1

**Comment by xavier-villelegier** [comment]
Hey @ajshukury, sorry for the delay ! We updated the dependencies, you should be able to clone from `master` now 👌  ! Feel free to reopen if it still doesn't work.
