### ISSUE TITLE
undefined is not a function (evaluating '_react3.default.forwardRef(forwardRef)')

### ISSUE THREAD

**Issue by filipetgomes** [react-native-elements/react-native-elements-app#63]
I keep getting this error.

I cloned the repository > deleted node_modules > npm install > npm start 

Then scanned the QR code, got the loading screen and then this error.

**Comment by DjarallahBrahim** [comment]
the same error !

**Comment by matwii** [comment]
Same error

**Comment by iRoachie** [comment]
Hey guys, we have to update the example app. It's using an old alpha version of react

**Comment by devaziz0** [comment]
Same here

**Comment by jaspermendiola** [comment]
Same

**Comment by goldfishinsky** [comment]
same
