### ISSUE TITLE
Eject Problem occured.

### ISSUE THREAD

**Issue by Biplovkumar** [react-native-elements/react-native-elements-app#64]
https://github.com/react-native-training/react-native-elements-app
I have used **react-native-elements-app** project as reference to build my own app, but i am facing problems when ejecting, need help.

**Comment by Biplovkumar** [comment]
My app is also on app store and play store but i want to add crashanalytics in this but still stuck in this.
What shouls i do ? 
all component are really awesome of react native elements.

**Comment by Monte9** [comment]
so the app that you have on the app store is a clone of this repo? Also it's possible that you are on an older version of Expo/CRNA & hence unable to eject.

Without seeing the error, I think the ejecting issue might be more relevant to the expo-cli repo.

**Comment by Biplovkumar** [comment]
no, not clone ,i have only follow struture and components which is used in react naative elements doc. when i was beginer in react native then i start learning from this repo and this app is really awesome app in . 
thanks for posting this repo.

please help if possible.
i have ejected successfully but when i run react native run android then not working.
what should i do ?
App.json : -

{
“expo”: {
“name”: “xxxxxxxxxxxxx”,
“description”: “xxxxxxxxxxxxx”,
“slug”: “xxxxxxxxxxxxx”,
“privacy”: “public”,
“sdkVersion”: “28.0.0”,
“version”: “1.0.0”,

"ios": {
  "bundleIdentifier": "xxxxxxxxxxxxx",
  "buildNumber": "1.0.0",
  "icon": "./assets/icons/icon_ios.png",
  "splash": {
    "image": "./assets/icons/loading.png",
    "resizeMode": "cover",
    "backgroundColor": "#8EBDB3"
  },
  "isTabletOnly": false,
  "supportsTablet": true
},
"android": {
  "package": "xxxxxxxxxxxxx",
  "versionCode": 1,
  "icon": "./assets/icons/icon.png",
  "splash": {
    "resizeMode": "cover",
    "ldpi": "./assets/icons/loading.png",
    "mdpi": "./assets/icons/loading.png",
    "hdpi": "./assets/icons/loading.png",
    "xhdpi": "./assets/icons/loading.png",
    "xxhdpi": "./assets/icons/loading.png",
    "xxxhdpi": "./assets/icons/loading.png",
    "backgroundColor": "#8EBDB3"
  }

},
"orientation": "portrait",
"primaryColor": "#cccccc",
"icon": "./assets/icons/icon_ios.png",
"splash": {
  "image": "./assets/icons/loading.png",
  "resizeMode": "cover",
  "backgroundColor": "#8EBDB3"
},
"packagerOpts": {
  "assetExts": [
    "ttf",
    "mp4"
  ],
  "config": "rn-cli.config.js"
}
}
}

Package.json File:-

{
“name”: “xxxxxxxxxxxxx”,
“version”: “1.0.0”,
“description”: “xxxxxxxxxxxxx”,
“author”: “xxxxxxxx”,
“private”: true,
“main”: “node_modules/expo/AppEntry.js”,
“dependencies”: {
“@expo/vector-icons”: “6.3.0”,
“@expo/videoplayer”: “^0.4.0”,
“axios”: “^0.18.0”,
“expo”: “^28.0.0”,
“lodash”: “^4.17.11”,
“moment”: “^2.22.2”,
“radio-button-react-native”: “^1.1.6”,
“react”: “16.3.1”,
“react-native”: “https://github.com/expo/react-native/archive/sdk-28.0.0.tar.gz”,
“react-native-animatable”: “^1.3.0”,
“react-native-circular-progress”: “^1.0.1”,
“react-native-countdown-component”: “^1.7.3”,
“react-native-elements”: “^1.0.0-beta5”,
“react-native-snap-carousel”: “^3.7.4”,
“react-navigation”: “^2.18.0”
},
“scripts”: {
“postinstall”: “git submodule update”,
“clean-install”: “rm -rf node_modules && npm cache clean --force && watchman watch-del-all && npm install”
}
}

**Comment by Monte9** [comment]
> react native run android then not working.

can you tell me the exact error you see on Android?

What about iOS? are you able to run that successfully?

**Comment by Biplovkumar** [comment]
$ react-native run-android
Scanning folders for symlinks in /home/xxxx/Documents/React_App/trydetach/xxxxxxxx/node_modules (9ms)
JS server already running.
Building and installing the app on the device (cd android && ./gradlew installDebug)...

> Task :app:compileDebugJavaWithJavac FAILED
/home/xxxxx/Documents/React_App/trydetach/xxxxxxxx/android/app/src/main/java/com/XXXXXX/MainApplication.java:5: error: cannot find symbol
import com.facebook.react.ReactApplication;
                         ^
  symbol:   class ReactApplication
  location: package com.facebook.react
/home/xxxxx/Documents/React_App/trydetach/xxxxxxxx/android/app/src/main/java/com/XXXXXX/MainApplication.java:6: error: cannot find symbol
import com.facebook.react.ReactNativeHost;
                         ^
  symbol:   class ReactNativeHost
  location: package com.facebook.react
/home/xxxxx/Documents/React_App/trydetach/xxxxxxxx/android/app/src/main/java/com/XXXXXX/MainApplication.java:14: error: cannot find symbol
public class MainApplication extends Application implements ReactApplication {
                                                            ^
  symbol: class ReactApplication
/home/xxxxx/Documents/React_App/trydetach/xxxxxxxx/android/app/src/main/java/com/XXXXXX/MainApplication.java:16: error: cannot find symbol
  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
                ^
  symbol:   class ReactNativeHost
  location: class MainApplication
/home/xxxxx/Documents/React_App/trydetach/xxxxxxxx/android/app/src/main/java/com/XXXXXX/MainApplication.java:36: error: cannot find symbol
  public ReactNativeHost getReactNativeHost() {
         ^
  symbol:   class ReactNativeHost
  location: class MainApplication
/home/xxxxx/Documents/React_App/trydetach/xxxxxxxx/android/app/src/main/java/com/XXXXXX/MainApplication.java:16: error: cannot find symbol
  private final ReactNativeHost mReactNativeHost = new ReactNativeHost(this) {
                                                       ^
  symbol:   class ReactNativeHost
  location: class MainApplication
/home/xxxxx/Documents/React_App/trydetach/xxxxxxxx/android/app/src/main/java/com/XXXXXX/MainApplication.java:35: error: method does not override or implement a method from a supertype
  @Override
  ^
/home/xxxxx/Documents/React_App/trydetach/xxxxxxxx/android/app/src/main/java/com/XXXXXX/MainActivity.java:5: error: MainActivity is not abstract and does not override abstract method getPackages() in ReactActivity
public class MainActivity extends ReactActivity {
       ^
8 errors


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
18 actionable tasks: 1 executed, 17 up-to-date
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/getting-started.html
Done in 5.79s.)

**Comment by xavier-villelegier** [comment]
If you want to eject without Expokit you must remove all usage of the `@expo` package too. Some docs about ejecting
https://docs.expo.io/versions/latest/expokit/eject
https://github.com/react-community/create-react-native-app/blob/master/EJECTING.md
