### ISSUE TITLE
Toggle Switches don't change

### ISSUE THREAD

**Issue by iRoachie** [react-native-elements/react-native-elements-app#71]
**Explain what you did**
I've been playing with the demonstration app using my Huawei Mate 10 Pro via Expo. On the Component form the binary toggle switch and the segmented control do not change when pressed.

**Expected behaviour**
I expect the input state to change

**Describe the bug**
Pressing the toggle switch just flashes, its state does not change (visually at least)

This effects

* Toggle Switch
* Segmented Control
* Checkbox

**To Reproduce**
Open the demo app on Expo, scroll down to the Switch row on the Components view. Tap it!

**Possible Solution**
Can you suggest a possible fix that would address this issue?

**Screenshots**

**Your Environment (please complete the following information):**

Huawei Mate 10 Pro
Android 8.0.0

**Comment by iRoachie** [comment]
Transferred from https://github.com/react-native-elements/react-native-elements/issues/1674

**Comment by anthonycmain** [comment]
Link doesnt work
