### ISSUE TITLE
Deploy RNW app to gh-pages

### ISSUE THREAD

**Issue by Monte9** [react-native-elements/react-native-elements-app#77]
Currently, I have it setup so that when you run `npm run deploy`, it uses the `gh-pages` npm package to publish the readme to the website here: https://react-native-elements.github.io/react-native-elements-app/

But we need the RNW project to be deployed on `gh-pages` instead.

@oxyii can you own this issue since you have it working on your fork already?

**Comment by oxyii** [comment]
@Monte9 Hmmm... I don't see Settings tab on repo. What you see in `Options -> GitHub Pages` block?

**Comment by oxyii** [comment]
Branch [gh-pages](https://github.com/react-native-elements/react-native-elements-app/tree/gh-pages) looks correct... And one more: in my case I install gh-pages globally. This is not app dep I think

**Comment by Monte9** [comment]
@oxyii let me add you as a collaborator on this project so you can push to master directly! 😉 

Also that will allow you to see the settings and configure the `gh-pages` as needed. Also if it's not app dep then feel free to remove it from `package.json`. 👍

**Comment by oxyii** [comment]
I can push into `gh-pages` branch but I cannot see Settings. Please check

![Выделение_001](https://user-images.githubusercontent.com/39907210/55214036-6f2cd000-5206-11e9-9c16-d282d3f4d28f.png)

**Comment by Monte9** [comment]
Updated! Looks like it worked! 🎉 

<img width="967" alt="Screen Shot 2019-03-29 at 12 01 55 AM" src="https://user-images.githubusercontent.com/7840686/55215116-e6864380-51b5-11e9-9276-55b384695c51.png">

**Comment by oxyii** [comment]
you beat me

![Выделение_001](https://user-images.githubusercontent.com/39907210/55215166-e6b02e80-5209-11e9-8eb3-ce206d1a0823.png)
