### ISSUE TITLE
Maintain a expo-free branch

### ISSUE THREAD

**Issue by ratson** [react-native-elements/react-native-elements-app#78]
Re https://github.com/react-native-elements/react-native-elements-app/issues/64, https://github.com/react-native-elements/react-native-elements-app/issues/49, it is clear that people have difficulties using this app without expo.

Is there any interests having a branch with expo removed?
I could prepare a PR if needed.

**Comment by iRoachie** [comment]
It would appear that the use case that we intended and what some persons are doing is different. In the issues you linked, persons are ejecting from the app to use it as a base for their own applications.

The main purpose of the example app is to show examples of react-native-elements components and how they can be combined and customized to make great user interfaces. This is in no means a starter kit, so not sure why persons would even be ejecting in the first place.

**Comment by ratson** [comment]
There could be many reasons why people are do so, I think one is people learning by modifying and it is not trivial to remove the expo-specific code. Or just missing high quality starter kits, so people find this could be a good one but eventually failed.

Feel free to close if it is out of scope.

**Comment by iRoachie** [comment]
It's a good discussion, I think expo is actually the default way to build react native applications as recommended by react-native docs

**Comment by ratson** [comment]
It is just about [different tradeoff](https://docs.expo.io/versions/latest/introduction/why-not-expo/).

Ejecting was supposed to help people move away from expo easily, but as it is certainly not the top priority of expo team, it ends up broken frequently and more difficult for more expo-specific code.

Having said that, expo is a good choice for beginner, just have to be aware the caveats.

**Comment by Monte9** [comment]
>  I think one is people learning by modifying and it is not trivial to remove the expo-specific code. 

> Or just missing high-quality starter kits, so people find this could be a good one but eventually failed.

I think both of these are valid concerns. I can def see myself, trying to eject this project just so I have a good starting point for my own project with everything setup such as navigation, web support, RNE etc.

Although I would take a different approach to solving this. I don't create a different branch makes it very hard to maintain and those two branches will go our of sync really quickly. What I suggest we do, is we can try to eject the app on master and fix any errors that we run into back into master.

That way, our master branch is an expo app that can be ejected and will work out fo the box. @ratson if you wanna give this a shot go for it, and then we can discuss the changes needed and see if this is something that's easy to support.

**Comment by ratson** [comment]
I [created a branch](https://github.com/ratson/react-native-elements-app/tree/expo-eject) with ejected code. When I run `yarn ios`, it gives the following errors,

```
Installing build/Build/Products/Debug-iphonesimulator/react-native-elements-app.app
An error was encountered processing the command (domain=NSPOSIXErrorDomain, code=22):
Failed to install the requested application
The bundle identifier of the application could not be determined.
Ensure that the application's Info.plist contains a value for CFBundleIdentifier.
Print: Entry, ":CFBundleIdentifier", Does Not Exist

Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/react-native-elements-app.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist


Error: Command failed: /usr/libexec/PlistBuddy -c Print:CFBundleIdentifier build/Build/Products/Debug-iphonesimulator/react-native-elements-app.app/Info.plist
Print: Entry, ":CFBundleIdentifier", Does Not Exist

    at checkExecSyncError (child_process.js:637:11)
    at Object.execFileSync (child_process.js:655:13)
    at ./node_modules/react-native/local-cli/runIOS/runIOS.js:208:1
```

I am not sure how to fix it.

**Comment by oxyii** [comment]
@ratson Check [this](https://stackoverflow.com/a/51487987)

**Comment by ratson** [comment]
@oxyii Thanks for the reference, the error seems related react-native version, which is a expo fork. 
I upgraded react-native to latest but still build with errors, you may continue the work from [the branch](https://github.com/ratson/react-native-elements-app/tree/expo-eject).

**Comment by oxyii** [comment]
@ratson Everything is easier than it seems. Have you seen [expo instructions](https://docs.expo.io/versions/latest/expokit/eject/#instructions) for elect? I draw your attention to link in p. 2. This must be done **before** eject. I believe that expo in the course of eject independently arranges bundle identifiers in the native code. And without updating RN version everything should compile correctly.

> I think expo is actually the default way to build react native applications as recommended by react-native docs

I completely agree with @iRoachie but if you definitely need a eject and you do everything according to the instructions and the errors will appear, please let us know with details

**Comment by ratson** [comment]
@oxyii I created https://github.com/react-native-elements/react-native-elements-app/pull/79
You may try `yarn eject:native` and run it, you should see the problem.

**Comment by ratson** [comment]
Close this as there will be no expo-free branch and I am not going to fix expo eject issue anymore.
