### ISSUE TITLE
Not working react-native-elements with web

### ISSUE THREAD

**Issue by liorizik** [react-native-elements/react-native-elements-app#80]
./node_modules/@react-navigation/native/dist/Scrollables.js
Module not found: Can't resolve 'react-native-gesture-handler' in 'C:\xampp\htdocs\react\native\react-native-elements-app\node_modules\@react-navigation\native\dist'

So can you help me to manage to react native

**Comment by Monte9** [comment]
@oxyii can you help with this issue?

**Comment by oxyii** [comment]
@liorizik Look: for all platforms support we include `react-native-gesture-handler` [twice](https://github.com/react-native-elements/react-native-elements-app/blob/master/package.json#L22-L23):

1. Last build of `1.0` for compatibility with `expo` 

2. Version `1.1` for web support

see [this comment](https://github.com/react-native-elements/react-native-elements-app/pull/74#issuecomment-475649064)

If you start web via `yarn web` (or `npm run web`) your project start via `react-app-rewired start` instead `react-scripts start`. 

`react-app-rewired` automatically load config overrides from `config-overrides.js`. [Lines with RNGH overrides](https://github.com/react-native-elements/react-native-elements-app/blob/master/config-overrides.js#L42-L44) too.

And I think that you try to start web via `react-scripts start` or your deps not all are installed

**Comment by oxyii** [comment]
@liorizik were you able to solve this issue? I'm still more inclined to missing deps...

**Comment by iRoachie** [comment]
Fixed now, with expo-web
