### ISSUE TITLE
Update native and web app

### ISSUE THREAD

**Issue by oxyii** [react-native-elements/react-native-elements-app#89]
We need to update [native app](https://expo.io/@monte9/react-native-elements-app) after Expo SDK upgrading @Monte9

**Comment by oxyii** [comment]
Web app too
![Screenshot at авг  12 03-35-25](https://user-images.githubusercontent.com/39907210/62841573-69fe8800-bcb2-11e9-919b-eb03f85adf9c.png)

**Comment by iRoachie** [comment]
Fixed.
